### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by 0xS4D** [klukule/SaveFileParseAPI#1]
I have two questions, the first one: Is it possible to migrate this project to JavaScript? Honestly, I have no idea how to implement the same thing in JavaScript, and it would be very useful for creating a new Save Editor.

Question two, just as there is an endpoint to convert a save to SQLite, is it possible to implement an endpoint to convert SQLite to .sav? Thank you very much in advance!

**Comment by klukule** [comment]
Hey there,

to answer your first question: no.... in more details, the new version of the savefile used Oodle compression, and that is a proprietary technology (hence the oocore dll in the repository) and as far as I know there is no wasm or javascript based implementation so it could be used in javascript.

to answer your second question: potentially... GVAS is just a data storage format and you could re-pack the SQLite data back into it, but your're going to have to write http endpoint for it, see <https://github.com/klukule/SaveFileParseAPI/blob/master/UnrealEngine.Gvas/SaveGameFile.cs#L46> this is the Save function, though I cannot guarantee that it will produce the same file. And you'll first have to re-compress the sqlite string. So with a bit of work you could indeed implement save routine. But this was not the scope of the project when I originally threw it together, so I did not implement it.
